name: Trigger
run-name: Trigger en acción
on: [push, pull_request, issues]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22.x
